spring:
  redis:
    host: localhost
    port: 6379
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/slowDelivery?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: HS9ffEi_MQWPEq5MWvmL # ????
            client-secret: K2PfTErz4W # ????
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - nickname
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  auth:
    token-expiration-msec: 864000000
    token-secret: F6bxqUhrYpOLvjgiATOi3S3YYZQyC2uHYrsiXqOikD+L6mbaBNWFIGProM1gbVSFw5/28BKHYkzyVUyc7o8HDUyBiBKDAMIftw1bf1bFVnuOgGEs80iabjfVcKgoUa+PnF1SdMsas3oR4Dgf0C80HsceUwWZipNg0m4vwjJuC1VZw3OMwY
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace